**Create a NumPy array with 5 elements ranging from 10 to 50 (inclusive).**

In [3]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
a[2]

30

**Create a 2d array of 3x3 size**

In [4]:
a = np.arange(1,13).reshape(2,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

**Reshape a given NumPy array arr of shape (2, 6) to shape (3, 4) without changing its data.**

In [5]:
aa = a.reshape(3,4)
aa

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Concatenate two NumPy arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.**

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b)).reshape(2,3)
c

array([[1, 2, 3],
       [4, 5, 6]])